modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/Lgmrszd/GourdsFix/issues"
[[mods]]
modId="gourds_fix"
version="${file.jarVersion}"
displayName="Gourds Fix"
updateJSONURL="https://api.modrinth.com/updates/gourds-fix/forge_updates.json"
displayURL="https://modrinth.com/mod/gourds-fix"
logoFile="icon.png"
credits="Credit for Multiloader template goes to Darkhax and jaredlll08 (and also Nik-Kot for some tweaks)"
authors="Lgmrszd"
description="""Enabling directional placement of Melons and Pumpkins, as well as making them grow horizontally.
Credit for Multiloader template goes to Darkhax and jaredlll08 (and also Nik-Kot for some tweaks)."""
[[dependencies.gourds_fix]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gourds_fix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gourds_fix]]
    modId="statement"
    mandatory=true
    versionRange="[4.2.5+1.19.2-forge,)"
    side="BOTH"
